export const AUTH_MESSAGES = {
    LOGIN_SUCCESS: 'Logged in successfully',
    REFRESH_SUCCESS: 'Token refreshed successfully',
    SESSION_SUCCESS: 'Session verified successfully',
    EMAIL_REQUIRED: 'Email is required from firebase token',
    USER_NOT_FOUND: 'User not found',
    LOGIN_REQUIRED: 'Please log in to get access',
    USER_DELETED: 'The user belonging to this token no longer exists',
    OTP_SENT: 'OTP sent successfully',
    INVALID_OTP: 'Invalid OTP',
    INVALID_TOKEN_FORMAT: 'Invalid token format',
    GOOGLE_VERIFICATION_FAILED: 'Failed to verify Google ID token',
    TOKEN_VERIFICATION_FAILED: 'Token verification failed',
    PHONE_REQUIRED: 'Phone number is required',
    PHONE_AND_OTP_REQUIRED: 'Phone number and OTP are required',
    ACTIVITY_LOGGED: 'Activity logged successfully',
    ACTIVITIES_FETCHED: 'Activities fetched successfully',
    SESSIONS_FETCHED: 'Sessions fetched successfully',
    SESSION_CREATED: 'Session created successfully',
    SESSION_TERMINATED: 'Session terminated successfully',
    ADDRESS_CREATED: 'Address created successfully',
    ADDRESSES_FETCHED: 'Addresses fetched successfully',
    ADDRESS_UPDATED: 'Address updated successfully',
    ADDRESS_DELETED: 'Address deleted successfully',
    BANNERS_FETCHED: 'Ad banners fetched successfully',
    OTP_EXPIRED: 'OTP has expired',
    USER_NOT_FOUND_FOR_OTP: 'No user found for this phone number',
    RATE_LIMIT_WAIT: 'Please wait 30 seconds before requesting a new OTP.',
};

export const AUTH_CONFIG = {
    GOOGLE_ISSUERS: ['https://accounts.google.com', 'accounts.google.com'],
    GOOGLE_TOKEN_INFO_URL: 'https://oauth2.googleapis.com/tokeninfo?id_token=',
    MOCK_OTP: '123456',
    DEFAULT_EMAIL_DOMAIN: '@shop.com',
    DEFAULT_USER_NAME_PREFIX: 'User ',
    TOKEN_SPLITTER: '.',
    EMAIL_SPLITTER: '@',
    EMPTY_FALLBACK: '',
    OTP_EXPIRY_MS: 300000,
    OTP_MESSAGE_TEMPLATE: 'Your Shop verification code is: {otp}',
    OTP_TYPE_LOGIN: 'LOGIN' as const,
};
