export const BUSINESS_MESSAGES = {
    BUSINESS_CREATED: 'Business created successfully',
    BUSINESS_UPDATED: 'Business updated successfully',
    BUSINESS_DELETED: 'Business deleted successfully',
    BRANCH_CREATED: 'Branch created successfully',
    BRANCH_UPDATED: 'Branch updated successfully',
    BRANCH_DELETED: 'Branch deleted successfully',
    DEPARTMENT_CREATED: 'Department created successfully',
    DEPARTMENT_UPDATED: 'Department updated successfully',
    DEPARTMENT_DELETED: 'Department deleted successfully',
    POST_CREATED: 'Post created successfully',
    POST_UPDATED: 'Post updated successfully',
    POST_DELETED: 'Post deleted successfully',
    SHIFT_CREATED: 'Shift created successfully',
    SHIFT_UPDATED: 'Shift updated successfully',
    SHIFT_DELETED: 'Shift deleted successfully',
    ROLE_CREATED: 'Role created successfully',
    ROLE_UPDATED: 'Role updated successfully',
    ROLE_DELETED: 'Role deleted successfully',
    EMPLOYEE_CREATED: 'Employee created successfully',
    EMPLOYEE_UPDATED: 'Employee updated successfully',
    EMPLOYEE_DELETED: 'Employee deleted successfully',
    JOIN_REQUEST_CREATED: 'Join request submitted successfully',
    JOIN_REQUESTS_FETCHED: 'Join requests fetched successfully',
    JOIN_REQUEST_APPROVED: 'Join request approved successfully',
    JOIN_REQUEST_REJECTED: 'Join request rejected successfully',
    INITIALIZE_SUCCESS: 'Business and branch initialized successfully',
    CONTEXT_FETCHED: 'User context fetched successfully',
    NOT_FOUND: 'Resource not found in business module',
    FORBIDDEN: 'You do not have permission to perform this action',
    ALREADY_JOINED: 'User is already associated with a business',
    JOIN_REQUEST_ALREADY_EXISTS: 'A pending join request already exists for this branch',
    JOIN_REQUEST_NOT_FOUND: 'Join request not found',
    JOIN_REQUEST_NOT_PENDING: 'Join request is not pending',
    BRANCH_NOT_FOUND: 'Branch not found',
    ROLE_NOT_FOUND: 'Role not found',
};

export const BUSINESS_DEFAULTS = {
    OWNER_ROLE: 'Owner',
    EMPLOYEE_ROLE: 'Employee',
    EMPLOYEE_POST: 'Employee',
    EMPLOYEE_DEPARTMENT: 'Operations',
    OWNER_POST: 'Owner',
    OWNER_DEPARTMENT: 'Management',
    GENERAL_SHIFT: 'General',
    GENERAL_SHIFT_START: '09:00',
    GENERAL_SHIFT_END: '18:00',
    ALL_PERMISSION: 'ALL',
    EMPLOYEE_PERMISSIONS: ['business:read', 'branch:read'] as readonly string[],
    EMPTY_BANK_DETAILS: { account_name: '', account_number: '', bank_name: '', ifsc_code: '' },
    EMPTY_ADDRESS: { street: '', city: '', state: '', zip: '', country: '' },
} as const;

export const BUSINESS_PERMISSIONS = [
    'business:read',
    'business:write',
    'branch:read',
    'branch:write',
    'department:read',
    'department:write',
    'post:read',
    'post:write',
    'shift:read',
    'shift:write',
    'role:read',
    'role:write',
    'employee:read',
    'employee:write',
] as const;
