export const BUSINESS_MESSAGES = {
    BUSINESS_CREATED: 'Business created successfully',
    BUSINESS_UPDATED: 'Business updated successfully',
    BUSINESS_DELETED: 'Business deleted successfully',
    BRANCH_CREATED: 'Branch created successfully',
    BRANCH_UPDATED: 'Branch updated successfully',
    BRANCH_DELETED: 'Branch deleted successfully',
    DEPARTMENT_CREATED: 'Department created successfully',
    DEPARTMENT_UPDATED: 'Department updated successfully',
    DEPARTMENT_DELETED: 'Department deleted successfully',
    POST_CREATED: 'Post created successfully',
    POST_UPDATED: 'Post updated successfully',
    POST_DELETED: 'Post deleted successfully',
    SHIFT_CREATED: 'Shift created successfully',
    SHIFT_UPDATED: 'Shift updated successfully',
    SHIFT_DELETED: 'Shift deleted successfully',
    ROLE_CREATED: 'Role created successfully',
    ROLE_UPDATED: 'Role updated successfully',
    ROLE_DELETED: 'Role deleted successfully',
    EMPLOYEE_CREATED: 'Employee created successfully',
    EMPLOYEE_UPDATED: 'Employee updated successfully',
    EMPLOYEE_DELETED: 'Employee deleted successfully',
    INITIALIZE_SUCCESS: 'Business and branch initialized successfully',
    CONTEXT_FETCHED: 'User context fetched successfully',
    NOT_FOUND: 'Resource not found in business module',
    FORBIDDEN: 'You do not have permission to perform this action',
};

export const BUSINESS_PERMISSIONS = [
    'business:read',
    'business:write',
    'branch:read',
    'branch:write',
    'department:read',
    'department:write',
    'post:read',
    'post:write',
    'shift:read',
    'shift:write',
    'role:read',
    'role:write',
    'employee:read',
    'employee:write',
] as const;
