name: mobile
description: Shop mobile application
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.2
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.2.0
  fluttertoast: ^8.2.10
  get_it: ^9.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  print_bluetooth_thermal: ^1.2.1
  esc_pos_utils_plus: ^2.0.4
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
