export const _MANUFACTURING_CONSTANTS = {
  _R_O_U_T_E_S: {
    _B_A_S_E: '/manufacturing',
    _B_O_M_S: '/boms',
    BOM_BY_ID: '/boms/:id',
    BOM_ITEMS: '/boms/:id/items',
    _B_A_T_C_H_E_S: '/batches',
    BATCH_BY_ID: '/batches/:id',
    BATCH_STATUS: '/batches/:id/status',
    QC_AUDITS: '/qc-audits',
    QC_AUDIT_BY_ID: '/qc-audits/:id',
    WASTAGE_LOGS: '/wastage-logs',
    WASTAGE_LOG_BY_ID: '/wastage-logs/:id',
  },
  _M_E_S_S_A_G_E_S: {
    BOM_CREATED: 'Bill of Material created successfully',
    BOMS_LISTED: 'BOMs fetched successfully',
    BOM_UPDATED: 'BOM updated successfully',
    BOM_DELETED: 'BOM deleted successfully',
    BOM_ITEM_ADDED: 'BOM item added successfully',
    BOM_ITEM_REMOVED: 'BOM item removed successfully',
    BATCH_CREATED: 'Production Batch created successfully',
    BATCHES_LISTED: 'Production Batches fetched successfully',
    BATCH_STATUS_UPDATED: 'Production Batch status updated successfully',
    QC_AUDIT_CREATED: 'QC Audit recorded successfully',
    QC_AUDITS_LISTED: 'QC Audits fetched successfully',
    WASTAGE_LOG_CREATED: 'Wastage Log recorded successfully',
    WASTAGE_LOGS_LISTED: 'Wastage Logs fetched successfully',
  },
  _E_R_R_O_R_S: {
    BOM_NOT_FOUND: 'Bill of Material not found',
    BATCH_NOT_FOUND: 'Production Batch not found',
    QC_AUDIT_NOT_FOUND: 'QC Audit not found',
    WASTAGE_LOG_NOT_FOUND: 'Wastage Log not found',
    INVALID_STATUS: 'Invalid status transition',
  },
  _S_T_A_T_U_S: {
    _B_A_T_C_H: {
      _P_L_A_N_N_E_D: 'PLANNED',
      IN_PROGRESS: 'IN_PROGRESS',
      _C_O_M_P_L_E_T_E_D: 'COMPLETED',
      _C_A_N_C_E_L_L_E_D: 'CANCELLED',
    },
    QC_AUDIT: {
      _P_A_S_S: 'PASS',
      _F_A_I_L: 'FAIL',
      _C_O_N_D_I_T_I_O_N_A_L: 'CONDITIONAL',
    },
  },
};
