export const _FINANCE_CONSTANTS = {
  _R_O_U_T_E_S: {
    _B_A_S_E: '/finance',
    _A_C_C_O_U_N_T_S: '/accounts',
    ACCOUNT_BY_ID: '/accounts/:id',
    _T_R_A_N_S_A_C_T_I_O_N_S: '/transactions',
    TRANSACTION_BY_ID: '/transactions/:id',
    _A_S_S_E_T_S: '/assets',
    ASSET_BY_ID: '/assets/:id',
    _R_O_Y_A_L_T_I_E_S: '/royalties',
    ROYALTY_BY_ID: '/royalties/:id',
    ROYALTY_PAY: '/royalties/:id/pay',
  },
  _M_E_S_S_A_G_E_S: {
    ACCOUNT_CREATED: 'Account created successfully',
    ACCOUNTS_LISTED: 'Accounts fetched successfully',
    ACCOUNT_UPDATED: 'Account updated successfully',
    TRANSACTION_CREATED: 'Transaction recorded successfully',
    TRANSACTIONS_LISTED: 'Transactions fetched successfully',
    ASSET_CREATED: 'Asset created successfully',
    ASSETS_LISTED: 'Assets fetched successfully',
    ASSET_UPDATED: 'Asset updated successfully',
    ROYALTY_CREATED: 'Royalty recorded successfully',
    ROYALTIES_LISTED: 'Royalties fetched successfully',
    ROYALTY_PAID: 'Royalty paid successfully',
  },
  _E_R_R_O_R_S: {
    ACCOUNT_NOT_FOUND: 'Account not found',
    TRANSACTION_NOT_FOUND: 'Transaction not found',
    ASSET_NOT_FOUND: 'Asset not found',
    ROYALTY_NOT_FOUND: 'Royalty not found',
    INSUFFICIENT_BALANCE: 'Insufficient account balance',
    INVALID_STATUS: 'Invalid status transition',
  },
  ACCOUNT_TYPE: {
    _C_A_S_H: 'CASH',
    _B_A_N_K: 'BANK',
    _E_X_P_E_N_S_E: 'EXPENSE',
    _I_N_C_O_M_E: 'INCOME',
    _P_A_Y_A_B_L_E: 'PAYABLE',
    _R_E_C_E_I_V_A_B_L_E: 'RECEIVABLE',
    _E_Q_U_I_T_Y: 'EQUITY',
  },
  TRANSACTION_TYPE: {
    _C_R_E_D_I_T: 'CREDIT',
    _D_E_B_I_T: 'DEBIT',
  },
};
