export const CUSTOMER_ORDERING_ROUTES = {
  MENU: "/menu",
  LOGIN: "/login",
  COMPLETE_PHONE: "/complete-phone",
} as const;

export const CUSTOMER_ORDERING_CARD_QR = {
  QUERY_KEY: "qr",
  QUERY_VALUE: "card",
  BRANCH_ID: "1783064192233",
  ORDER_TYPE: "DELIVERY",
} as const;

export const CUSTOMER_ORDERING_STORAGE_KEYS = {
  BRANCH_ID: "qr_branch_id",
  TABLE_ID: "qr_table_id",
  TABLE_SIDE_ID: "qr_table_side_id",
  ORDER_TYPE: "qr_order_type",
  CART: "customer_ordering_cart",
  LADYLUCK_DISCOUNT_ID: "customer_ordering_ladyluck_discount_id",
} as const;

export const CUSTOMER_ORDERING_QUERY_KEYS = {
  BRANCH_ID: "branch_id",
  TABLE_ID: "table_id",
  TABLE_SIDE_ID: "table_side_id",
  ORDER_TYPE: "order_type",
} as const;

export const CUSTOMER_ORDERING_LEGACY_QUERY_KEYS = {
  BRANCH_ID: "b",
  TABLE_ID: "t",
  TABLE_SIDE_ID: "s",
} as const;

export const CUSTOMER_ORDERING_ENDPOINTS = {
  MENU: "/catalog/menu",
  PUBLIC_TABLES: "/pos-kds/public/tables",
  ORDERS: "/pos-kds/orders",
  MY_ORDERS: "/pos-kds/orders/my",
  LADYLUCK_SUMMARY: "/ladyluck/summary",
  LADYLUCK_SCRATCH_CARD: "/ladyluck/scratch-cards",
} as const;

export const CUSTOMER_ORDERING_TEXT = {
  APP_TITLE: "POS Terminal",
  MENU_HERO_TITLE: "Menu",
  MENU_HERO_SUBTITLE: "Fresh picks from LadyLuck kitchen",
  FEATURED_DISH: "Featured dish",
  ITEMS_AVAILABLE: "items available",
  CATEGORY_SELECTED: "Selected",
  CATEGORY_BROWSE: "Browse",
  ALL_ITEMS: "All Items",
  EMPTY_MENU: "No menu items found",
  CART_EMPTY: "Cart is empty",
  CART_TITLE: "Your cart",
  CART_ITEMS_TITLE: "Items",
  VIEW_CART: "View cart",
  ORDER_NOW: "Order Now",
  FAVORITE_ITEM: "Favorite item",
  PLACE_ORDER: "Place order",
  LOGIN_TO_ORDER: "Login to place order",
  ORDER_PLACED: "Order placed successfully",
  ORDER_FAILED: "Unable to place order",
  PROFILE_LOADING: "Loading your profile. Please try again.",
  MENU_FAILED: "Unable to load menu",
  TABLE_CONTEXT: "Table order",
  DELIVERY_CONTEXT: "Delivery order",
  TAKEAWAY_CONTEXT: "Takeaway order",
  SELECT_SEATS: "Select seats",
  SELECT_ADDRESS: "Select address",
  ADDRESS_REQUIRED: "Select an address before placing delivery order",
  SEATS_REQUIRED: "Select at least one table side",
  OFFERS_TITLE: "Coupons and offers",
  OFFER_ONE_TITLE: "Welcome savings",
  OFFER_ONE_BODY:
    "Login to view eligible coupons and account offers before payment.",
  OFFER_TWO_TITLE: "Restaurant offers",
  OFFER_TWO_BODY:
    "Available offers are refreshed from your account at checkout.",
  PREVIOUS_ORDERS: "Previous orders",
  PREVIOUS_ORDERS_BODY:
    "Login to show your previous orders from this restaurant.",
  ITEM_COUNT: "items",
  SUBTOTAL: "Subtotal",
  TAX: "Tax",
  PAYABLE: "Payable",
  CONTINUE: "Continue",
  BILLING: "Billing",
  ORDER_RECEIPT: "Receipt",
  RECEIPT_STORE_NAME: "LadyLuck",
  RECEIPT_ORDER_MODE: "Web order",
  RECEIPT_SUBTOTAL: "Subtotal",
  RECEIPT_FINAL_PAYING: "Final paying",
  RECEIPT_ESTIMATE: "Estimated bill",
  LADYLUCK_TITLE: "Ladyluck Rewards",
  LADYLUCK_POINTS: "Ladyluck points",
  LADYLUCK_POINTS_SHORT: "points",
  LADYLUCK_MASCOT: "L",
  LADYLUCK_SCRATCH_READY: "Scratch card ready",
  LADYLUCK_SCRATCH_BODY: "Scratch to unlock a discount for this order.",
  LADYLUCK_SCRATCH_ACTION: "Scratch now",
  LADYLUCK_APPLIED: "Ladyluck applied",
  LADYLUCK_UNLOCKED: "Unlocked reward",
  LADYLUCK_POPUP_READY_TITLE: "Your scratch card is ready",
  LADYLUCK_POPUP_READY_CODE: "LADYLUCK",
  LADYLUCK_POPUP_READY_BODY: "Scratch this card to reveal your discount for this order.",
  LADYLUCK_POPUP_UNLOCKED_TITLE: "Discount unlocked",
  LADYLUCK_POPUP_UNLOCKED_BODY: "Your Ladyluck discount is active and will be applied at checkout when the order is eligible.",
  LADYLUCK_POPUP_ACTION: "Got it",
  LADYLUCK_YOU_SAVED: "YOU SAVED",
  LADYLUCK_SAVED_WITH: "Saved with Ladyluck",
  LADYLUCK_CODE_PREFIX: "#",
  LADYLUCK_ADD_MORE: "Add more to use this reward",
  LADYLUCK_POINTS_TO_GO: "more points to unlock a scratch card",
  LADYLUCK_MILESTONE_UNLOCKED: "Milestone unlocked",
  LADYLUCK_NO_CARD: "Earn 500 points to unlock a scratch card.",
  LADYLUCK_LOADING: "Loading rewards",
  LADYLUCK_DISCOUNT: "Ladyluck discount",
  LADYLUCK_MINIMUM: "Minimum order",
  LADYLUCK_SCRATCH_FAILED: "Unable to scratch card",
  ORDERS: "Orders",
  MORE: "More",
  DELIVERY_FALLBACK: "Delivery",
  TABLE_FALLBACK: "Table",
  SIDE_PREFIX: "Side",
  CHANGE: "Change",
  CONTEXT_MISSING: "Scan a valid QR code to load this restaurant menu.",
  SELECT_SALE_MODE: "Select sale mode",
  DEFAULT_SALE_MODE: "Regular",
} as const;

export const CUSTOMER_ORDER_TYPES = {
  DINE_IN: "DINE_IN",
  DELIVERY: "DELIVERY",
  TAKEAWAY: "TAKEAWAY",
} as const;

export const CUSTOMER_ORDERING_DEFAULTS = {
  ACTIVE_CATEGORY_ID: "all",
  TAX_RATE: 0.1,
  TABLE_SIDE_COUNT: 4,
  EMPTY_IMAGE: "",
  ORDER_CREATE_TIMEOUT_MS: 30000,
  ORDER_CONFIRMATION_WINDOW_MS: 120000,
  ORDER_CONFIRMATION_RETRY_COUNT: 3,
  ORDER_CONFIRMATION_RETRY_DELAY_MS: 1200,
  ORDER_AMOUNT_TOLERANCE: 1,
  LADYLUCK_POINTS_PER_CARD: 500,
} as const;
