export const _POS_KDS_CONSTANTS = {
  _R_O_U_T_E_S: {
    _B_A_S_E: '/pos-kds',
    PUBLIC_TABLES: '/public/tables',
    _O_R_D_E_R_S: '/orders',
    CUSTOMER_BY_PHONE: '/customers/:phone',
    CUSTOMER_RESOLVE_PHONE: '/customers/resolve-phone',
    ORDER_BY_ID: '/orders/:id',
    ORDER_PAY: '/orders/:id/pay',
    ORDER_REFUND: '/orders/:id/refund',
    ORDER_CANCEL: '/orders/:id/cancel',
    _T_A_B_L_E_S: '/tables',
    TABLE_BY_ID: '/tables/:id',
    _T_A_B_L_E_Z_O_N_E_S: '/table-zones',
    TABLE_ZONE_BY_ID: '/table-zones/:id',
    _K_O_T_S: '/kots',
    KOT_BY_ID: '/kots/:id',
    KOT_STATUS: '/kots/:id/status',
    KOT_ITEMS: '/kots/:id/items',
    _P_A_Y_M_E_N_T_S: '/payments',
    PAYMENT_BY_ID: '/payments/:id',
  },
  _M_E_S_S_A_G_E_S: {
    ORDER_CREATED: 'Order created successfully',
    ORDERS_LISTED: 'Orders fetched successfully',
    ORDER_UPDATED: 'Order updated successfully',
    ORDER_PAID: 'Order paid successfully',
    ORDER_REFUNDED: 'Order refunded successfully',
    ORDER_CANCELLED: 'Order cancelled successfully',
    TABLE_CREATED: 'Table created successfully',
    TABLES_LISTED: 'Tables fetched successfully',
    TABLE_UPDATED: 'Table updated successfully',
    TABLE_DELETED: 'Table deleted successfully',
    TABLE_ZONE_CREATED: 'Table zone created successfully',
    TABLE_ZONES_LISTED: 'Table zones fetched successfully',
    TABLE_ZONE_UPDATED: 'Table zone updated successfully',
    TABLE_ZONE_DELETED: 'Table zone deleted successfully',
    KOT_CREATED: 'KOT created successfully',
    KOTS_LISTED: 'KOTs fetched successfully',
    KOT_STATUS_UPDATED: 'KOT status updated successfully',
    KOT_ITEMS_LISTED: 'KOT items fetched successfully',
    PAYMENT_CREATED: 'Payment recorded successfully',
    PAYMENTS_LISTED: 'Payments fetched successfully',
    PAYMENT_UPDATED: 'Payment updated successfully',
    CUSTOMER_RETRIEVED: 'Customer retrieved successfully',
  },
  _E_R_R_O_R_S: {
    ORDER_NOT_FOUND: 'Order not found',
    TABLE_NOT_FOUND: 'Table not found',
    TABLE_ZONE_NOT_FOUND: 'Table zone not found',
    KOT_NOT_FOUND: 'KOT not found',
    PAYMENT_NOT_FOUND: 'Payment not found',
    INVALID_STATUS: 'Invalid status transition',
    BRANCH_REQUIRED: 'Branch ID is required',
    MENU_ITEM_NOT_FOUND: 'Menu item not found',
    SALE_MODE_NOT_FOUND: 'Sale mode not found',
    TABLE_SESSION_NOT_FOUND: 'Table session not found',
    TABLE_SESSION_CLOSED: 'Table session is already closed',
    TABLE_SEATS_OCCUPIED: 'Selected table seats are already occupied by another active bill',
  },
  _D_E_F_A_U_L_T_S: {
    SALE_MODE_LABEL: 'Regular',
  },
  _S_T_A_T_U_S: {
    _O_R_D_E_R: {
      _P_E_N_D_I_N_G: 'PENDING',
      _P_A_I_D: 'PAID',
      _C_A_N_C_E_L_L_E_D: 'CANCELLED',
      _R_E_F_U_N_D_E_D: 'REFUNDED',
    },
    _K_O_T: {
      _P_E_N_D_I_N_G: 'PENDING',
      _P_R_E_P_A_R_I_N_G: 'PREPARING',
      _R_E_A_D_Y: 'READY',
      _S_E_R_V_E_D: 'SERVED',
      _C_A_N_C_E_L_L_E_D: 'CANCELLED',
    },
    _P_A_Y_M_E_N_T: {
      _S_U_C_C_E_S_S: 'SUCCESS',
      _F_A_I_L_E_D: 'FAILED',
      _R_E_F_U_N_D_E_D: 'REFUNDED',
    },
  },
};
