export const _INVENTORY_CONSTANTS = {
  _R_O_U_T_E_S: {
    _B_A_S_E: '/inventory',
    _S_U_P_P_L_I_E_R_S: '/suppliers',
    SUPPLIER_BY_ID: '/suppliers/:id',
    ITEM_CATEGORIES: '/item-categories',
    _I_T_E_M_S: '/items',
    ITEM_BY_ID: '/items/:id',
    ITEM_VARIANTS: '/items/:id/variants',
    _V_A_R_I_A_N_T_S: '/variants',
    VARIANT_BY_ID: '/variants/:id',
    _U_O_M: '/uom',
    UOM_CONVERSIONS: '/uom-conversions',
    PURCHASE_ORDERS: '/purchase-orders',
    PURCHASE_ORDER_BY_ID: '/purchase-orders/:id',
    PURCHASE_ORDER_SEND: '/purchase-orders/:id/send',
    PURCHASE_ORDER_RECEIVE: '/purchase-orders/:id/receive',
    PURCHASE_ORDER_RECEIPTS: '/purchase-orders/:id/receipts',
    PURCHASE_ORDER_RETURNS: '/purchase-orders/:id/returns',
    PURCHASE_ORDER_RETURN_BY_ID: '/purchase-orders/:id/returns/:returnId',
    _S_T_O_C_K: '/stock',
    STOCK_LEDGER: '/stock-ledger',
    _U_S_A_G_E: '/usage',
    _W_A_S_T_A_G_E: '/wastage',
    STOCK_TRANSFERS: '/stock-transfers',
    STOCK_TRANSFER_BY_ID: '/stock-transfers/:id',
    STOCK_TRANSFER_RECEIVE: '/stock-transfers/:id/receive',
  },
  _M_E_S_S_A_G_E_S: {
    SUPPLIER_CREATED: 'Supplier created successfully',
    SUPPLIERS_LISTED: 'Suppliers fetched successfully',
    SUPPLIER_UPDATED: 'Supplier updated successfully',
    SUPPLIER_DELETED: 'Supplier deleted successfully',
    ITEM_CATEGORY_CREATED: 'Item category created successfully',
    ITEM_CATEGORIES_LISTED: 'Item categories fetched successfully',
    ITEM_CREATED: 'Item created successfully',
    ITEMS_LISTED: 'Items fetched successfully',
    ITEM_UPDATED: 'Item updated successfully',
    ITEM_DELETED: 'Item deleted successfully',
    UOM_CREATED: 'UOM created successfully',
    UOMS_LISTED: 'UOMs fetched successfully',
    UOM_CONVERSION_CREATED: 'UOM conversion created successfully',
    UOM_CONVERSIONS_LISTED: 'UOM conversions fetched successfully',
    VARIANT_CREATED: 'Item variant created successfully',
    VARIANTS_LISTED: 'Item variants fetched successfully',
    VARIANT_UPDATED: 'Item variant updated successfully',
    PO_CREATED: 'Purchase order created successfully',
    POS_LISTED: 'Purchase orders fetched successfully',
    PO_SENT: 'Purchase order sent successfully',
    PO_RECEIVED: 'Purchase order received successfully',
    RECEIPTS_LISTED: 'Goods receipts fetched successfully',
    RETURN_CREATED: 'Vendor return created successfully',
    RETURNS_LISTED: 'Vendor returns fetched successfully',
    RETURN_UPDATED: 'Vendor return updated successfully',
    STOCK_LEVELS_FETCHED: 'Stock levels fetched successfully',
    STOCK_LEDGER_FETCHED: 'Stock ledger fetched successfully',
    USAGE_LOGGED: 'Usage logged successfully',
    WASTAGE_LOGGED: 'Wastage logged successfully',
    TRANSFER_CREATED: 'Stock transfer created successfully',
    TRANSFERS_LISTED: 'Stock transfers fetched successfully',
    TRANSFER_RECEIVED: 'Stock transfer received successfully',
    WASTAGE_LOGS_LISTED: 'Wastage logs fetched successfully',
  },
  _E_R_R_O_R_S: {
    SUPPLIER_NOT_FOUND: 'Supplier not found',
    ITEM_CATEGORY_NOT_FOUND: 'Item category not found',
    ITEM_NOT_FOUND: 'Item not found',
    VARIANT_NOT_FOUND: 'Item variant not found',
    UOM_NOT_FOUND: 'UOM not found',
    PO_NOT_FOUND: 'Purchase order not found',
    RETURN_NOT_FOUND: 'Vendor return not found',
    TRANSFER_NOT_FOUND: 'Stock transfer not found',
    INSUFFICIENT_STOCK: 'Insufficient stock',
    INVALID_STATUS: 'Invalid status transition',
  },
  _S_T_A_T_U_S: {
    _A_C_T_I_V_E: 'ACTIVE',
    _D_R_A_F_T: 'DRAFT',
    _S_E_N_T: 'SENT',
    PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
    _R_E_C_E_I_V_E_D: 'RECEIVED',
    _C_A_N_C_E_L_L_E_D: 'CANCELLED',
    _P_E_N_D_I_N_G: 'PENDING',
    _A_P_P_R_O_V_E_D: 'APPROVED',
    _R_E_J_E_C_T_E_D: 'REJECTED',
    _R_E_F_U_N_D_E_D: 'REFUNDED',
    _D_I_S_P_A_T_C_H_E_D: 'DISPATCHED',
    LOST_IN_TRANSIT: 'LOST_IN_TRANSIT',
  },
  STOCK_TRANS_TYPE: {
    _P_U_R_C_H_A_S_E: 'PURCHASE',
    _S_A_L_E: 'SALE',
    PRODUCTION_IN: 'PRODUCTION_IN',
    PRODUCTION_OUT: 'PRODUCTION_OUT',
    _W_A_S_T_A_G_E: 'WASTAGE',
    TRANSFER_IN: 'TRANSFER_IN',
    TRANSFER_OUT: 'TRANSFER_OUT',
    _R_E_T_U_R_N: 'RETURN',
    _A_D_J_U_S_T_M_E_N_T: 'ADJUSTMENT',
  },
};
