export const _CORE_HR_CONSTANTS = {
  _R_O_U_T_E_S: {
    _A_U_T_H: '/auth',
    _L_O_G_I_N: '/auth/login',
    SEND_OTP: '/auth/send-otp',
    _M_E: '/auth/me',
    _B_R_A_N_C_H: '/branch',
    BRANCH_SEARCH: '/branch/search',
    BRANCH_JOIN_REQUEST: '/branch/join-request',
    BRANCH_JOIN_REQUESTS: '/branch/join-requests',
    BRANCH_JOIN_REQUEST_APPROVE: '/branch/join-requests/:id/approve',
    BRANCH_JOIN_REQUEST_REJECT: '/branch/join-requests/:id/reject',
    _E_M_P_L_O_Y_E_E_S: '/employees',
    EMPLOYEE_BY_ID: '/employees/:id',
    _D_E_P_A_R_T_M_E_N_T_S: '/departments',
    _R_O_L_E_S: '/roles',
    _P_O_S_T_S: '/posts',
    _S_H_I_F_T_S: '/shifts',
    TIME_LOGS: '/time-logs',
    CLOCK_IN: '/time-logs/clock-in',
    CLOCK_OUT: '/time-logs/:id/clock-out',
    CASH_REGISTERS: '/cash-registers',
    OPEN_CASH_REGISTER: '/cash-registers/:id/open',
    CLOSE_CASH_REGISTER: '/cash-registers/:id/close',
    USER_LOGS: '/user-logs',
  },
  _M_E_S_S_A_G_E_S: {
    OTP_SENT: 'OTP sent successfully',
    LOGIN_SUCCESS: 'Login successful',
    GET_ME_SUCCESS: 'User fetched successfully',
    BRANCH_CREATED: 'Branch created successfully',
    BRANCHES_FOUND: 'Branches fetched successfully',
    JOIN_REQUEST_CREATED: 'Join request submitted successfully',
    JOIN_REQUESTS_LISTED: 'Join requests fetched successfully',
    JOIN_REQUEST_APPROVED: 'Join request approved successfully',
    JOIN_REQUEST_REJECTED: 'Join request rejected successfully',
    EMPLOYEES_LISTED: 'Employees fetched successfully',
    EMPLOYEE_CREATED: 'Employee created successfully',
    EMPLOYEE_UPDATED: 'Employee updated successfully',
    EMPLOYEE_DELETED: 'Employee deleted successfully',
    DEPARTMENTS_LISTED: 'Departments fetched successfully',
    DEPARTMENT_CREATED: 'Department created successfully',
    ROLES_LISTED: 'Roles fetched successfully',
    ROLE_CREATED: 'Role created successfully',
    POSTS_LISTED: 'Posts fetched successfully',
    POST_CREATED: 'Post created successfully',
    SHIFTS_LISTED: 'Shifts fetched successfully',
    SHIFT_CREATED: 'Shift created successfully',
    TIME_LOGS_LISTED: 'Time logs fetched successfully',
    CLOCKED_IN: 'Clocked in successfully',
    CLOCKED_OUT: 'Clocked out successfully',
    CASH_REGISTERS_LISTED: 'Cash registers fetched successfully',
    CASH_REGISTER_CREATED: 'Cash register created successfully',
    CASH_REGISTER_OPENED: 'Cash register opened successfully',
    CASH_REGISTER_CLOSED: 'Cash register closed successfully',
    USER_LOGS_LISTED: 'User logs fetched successfully',
  },
  _E_R_R_O_R_S: {
    INVALID_OTP: 'Invalid OTP',
    OTP_EXPIRED: 'OTP expired or not requested',
    MISSING_CREDENTIALS: 'Either idToken or phone_number and otp are required',
    INVALID_TOKEN: 'Invalid or expired token',
    TOKEN_MISSING: 'Authorization token is missing',
    USER_NOT_FOUND: 'User not found',
    BRANCH_NOT_FOUND: 'Branch not found',
    ROLE_NOT_FOUND: 'Role not found',
    EMPLOYEE_NOT_FOUND: 'Employee not found',
    DEPARTMENT_NOT_FOUND: 'Department not found',
    JOIN_REQUEST_NOT_FOUND: 'Join request not found',
    CASH_REGISTER_NOT_FOUND: 'Cash register not found',
    TIME_LOG_NOT_FOUND: 'Time log not found',
    PENDING_REQUEST_EXISTS: 'A pending join request already exists for this branch',
    NOT_AN_EMPLOYEE: 'You are not an employee of this branch',
    PERMISSION_DENIED: 'You do not have permission to perform this action',
    _U_N_A_U_T_H_O_R_I_Z_E_D: 'Unauthorized',
    EMPLOYEE_ALREADY_EXISTS: 'Employee already exists',
    NOT_CLOCKED_IN: 'Employee is not clocked in',
    ALREADY_CLOCKED_IN: 'An open time log already exists for this employee',
    FIREBASE_TOKEN_INVALID: 'Firebase ID token is invalid',
  },
  _F_I_E_L_D_S: {
    _U_I_D: 'uid',
    BRANCH_ID: 'branch_id',
    _N_A_M_E: 'name',
    _P_H_O_N_E: 'phone',
    _E_M_A_I_L: 'email',
    _A_V_A_T_A_R: 'avatar',
    _C_O_D_E: 'code',
    IS_HQ: 'is_hq',
    _M_E_S_S_A_G_E: 'message',
    _S_T_A_T_U_S: 'status',
    REVIEWED_BY: 'reviewed_by',
    ROLE_ID: 'role_id',
    DEPARTMENT_ID: 'department_id',
    POST_ID: 'post_id',
    SHIFT_ID: 'shift_id',
    _P_E_R_M_I_S_S_I_O_N_S: 'permissions',
    _D_E_S_C_R_I_P_T_I_O_N: 'description',
    START_TIME: 'start_time',
    END_TIME: 'end_time',
    EMPLOYEE_ID: 'employee_id',
    CLOCK_IN: 'clock_in',
    CLOCK_OUT: 'clock_out',
    TOTAL_HOURS: 'total_hours',
    REGISTER_NAME: 'register_name',
    MAC_ADDRESS: 'mac_address',
    EXPECTED_CASH: 'expected_cash',
    ACTUAL_CASH: 'actual_cash',
    OPENED_BY: 'opened_by',
    CLOSED_BY: 'closed_by',
    ID_TOKEN: 'idToken',
    _Q_U_E_R_Y: 'query',
    id: 'id',
  },
  _J_W_T: {
    BEARER_PREFIX: 'Bearer',
    AUTH_HEADER: 'authorization',
  },
  _P_E_R_M_I_S_S_I_O_N_S: {
    _A_L_L: 'ALL',
    EMPLOYEE_WRITE: 'employee:write',
    OWNER_ROLE: 'Owner',
  },
  _P_R_I_S_M_A: {
    JOIN_REQUEST_STATUS_PENDING: 'PENDING',
    JOIN_REQUEST_STATUS_APPROVED: 'APPROVED',
    JOIN_REQUEST_STATUS_REJECTED: 'REJECTED',
  },
  OTP_MIN: 100000,
  OTP_MAX: 999999,
  OTP_EXPIRY_MS: 5 * 60 * 1000,
  OTP_SMS_BODY: 'Your Shop verification code is: ',
  _D_E_F_A_U_L_T_S: {
    UNKNOWN_USER: 'Unknown',
  },
};


